### ISSUE TITLE
manca gitignore

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/tipi_avanzati#1]
manca gitignore

**Comment by LuigiVessella** [comment]
git che? ahah

**Comment by FabioZTessitore** [comment]
Forse non hai letto tutto nella prima parte

**Comment by LuigiVessella** [comment]
Si prof però a me non esce..c'è solo gitconfig..Anche se provo a rifare email e password

**Comment by LuigiVessella** [comment]
ls -a nemmeno esce

**Comment by FabioZTessitore** [comment]
Ma che stai dicendo?

Il 31 gen 2017 8:42 PM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
gitignore non c'è..c'è solo gitconfig come file

**Comment by FabioZTessitore** [comment]
È evidente che non sai di che stiamo parlando. Ti avevo detto di andare a
leggere nella prima parte

Il martedì 31 gennaio 2017, LuigiVessella <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Ma io sono andato a leggere..Anche ruzzon sta leggendo

**Comment by LuigiVessella** [comment]
La prima volta che si utilizza git su un computer è opportuno effettuare una configurazione. Le informazioni minime da fornire sono il nome utente e l’email.

$ git config --global user.name "YOUR NAME HERE"
$ git config --global user.email "YOUR EMAIL HERE"

: Ho provato, ma non succede nulla.

: Dice? Ha provato a cercare nella sua home? dovrebbe essere stato creato un file (nascosto) .gitconfig

$ cd
$ ls -a
... .gitignore ...
$ cat .gitignore
[user]
	email = LA_SUA_EMAIL
	name = IL_SUO_NOME_UTENTE

e che altro devo capire?

**Comment by FabioZTessitore** [comment]
Ma che c'entra questa roba?

Il 31 gen 2017 9:22 PM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
io questo ho letto..Non vedo altre cose che parlano di gitignore

**Comment by FabioZTessitore** [comment]
Quello che hai letto NON parla di gitignore. Continua a cercare, è la volta
buona che leggi

Il 31 gen 2017 9:26 PM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Gitingore l'ho ignore 
davvero

**Comment by LuigiVessella** [comment]
Ok ho messo gitignore, ma per i file eseguibili come posso fare? Devo scrivere sempre il loro nome?

**Comment by FabioZTessitore** [comment]
Si

Il 1 feb 2017 3:20 PM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Ok ho fatto e funziona. L'esercizio è ok?
