### ISSUE TITLE
cast

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/tipi_avanzati#2]
il programma va bene. però ricordati di mettere i nomi dei file in minuscolo e aggiusta gli spazi

**Comment by LuigiVessella** [comment]
Ok..ho caricato anche address e come sempre solo dopo ho letto questo consiglio quindi da ora i nomi saranno piccoli..Per gli spazi ora correggo

**Comment by LuigiVessella** [comment]
Fatto
