### ISSUE TITLE
sommavett

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/tipi_avanzati#4]
Attenzione alla media

**Comment by LuigiVessella** [comment]
Ma perchè se do 16 mi da 5 come media? Dove sbaglio?

**Comment by FabioZTessitore** [comment]
Ti avevo detto di fare attenzione

**Comment by LuigiVessella** [comment]
Si si ho capito l'errore poi quando torno a casa lo correggo

Il 03 feb 2017 10:37 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Fatto prof

**Comment by LuigiVessella** [comment]
Ora i risultati sono come dovrebbero
