### ISSUE TITLE
sumvett

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/tipi_avanzati#5]
c'è un errore gravissimo

**Comment by LuigiVessella** [comment]
riguardante?

**Comment by FabioZTessitore** [comment]
Prova a cercarlo

Il 6 feb 2017 9:59 PM, "LuigiVessella" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
aggiustiamo?

**Comment by LuigiVessella** [comment]
Fatto..Tra poco creo la nuova repo per ncurses etc..

2017-02-09 13:58 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
